### PR TITLE
fix: immutable resource status

### LINKED ISSUE #1120: Bug: Immutable "ResourcesSubmitted" error message is bad before an object has succeeded
### Bug description:
When an immutable template stamps objects, if none have succeeded, the workload's `ResourcesSubmitted` condition reads:
```
waiting to read value [<no jsonpath context>] from resource [testobjs.test.run/test-resource-6f4tj] in namespace [testns-px5k7]
```

Instead, a new error should be created to indicate that no created object is yet healthy.

### Steps to reproduce:
Run `go run -modfile hack/tools/go.mod github.com/onsi/ginkgo/ginkgo tests/integration/supplychain` in [this branch](https://github.com/vmware-tanzu/cartographer/tree/immutable-no-healthy-error) to see the bad output.
**Note: This is not an example of a test that should go green when the story is complete. `itResultsInAHealthyWorkload()` should be deleted.**

### Expected behavior:
*Discuss with team*

### PR DESCRIPTION
**Pull request by waciumawanjohi**
[PR requirements]: https://github.com/vmware-tanzu/cartographer/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines

## Changes proposed by this PR

Resolves #1120

Also resolves an issue where `lifecycle:tekton` resources would remain in a healthy state, even if the most recent object was in an unknown or unhealthy state.

## Release Note

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- [x] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`
- [ ] Removed non-atomic or `wip` commits
- ~[ ] Filled in the [Release Note](#Release-Note) section above~
- ~[ ] Modified the docs to match changes~

### CODE REVIEW

File: tests/integration/supplychain/workload_reconciler_test.go [hunk 1]
```diff
@@ -683,23 +687,50 @@ var _ = Describe("WorkloadReconciler", func() {
...
 
 						workload := &v1alpha1.Workload{}
 						err := c.Get(ctx, client.ObjectKey{Name: "workload-joe", Namespace: testNS}, workload)
 						Expect(err).NotTo(HaveOccurred())
+
+						Expect(workload.Status.Conditions).To(MatchAllElements(getConditionOfType, Elements{
+							"SupplyChainReady": MatchFields(IgnoreExtras, Fields{
+								"Status": Equal(metav1.ConditionTrue),
+							}),
+							"ResourcesSubmitted": MatchFields(IgnoreExtras, Fields{
```
Comment (squeedee) [inline tests/integration/supplychain/workload_reconciler_test.go:716]: I'm concerned by the confusion this might create in the top level conditions:
```
  Type: ResourcesSubmitted
  Status: False
  Reason: NoHealthyStampedObjectsFound
```

It reads to me like "nothing across the supply chain is healthy" (I can logically deduce that this is not what it means, but I'd still be forced to think about it)

Perhaps: 
```
  Type: ResourcesSubmitted
  Status: False
  Reason: NoHealthyStampedImmutableObjectFound
```

**Review by squeedee — APPROVED** [review]
