### PR TITLE
Simplify template jsonpath errors

### LINKED ISSUE #814: Interpolation errors should not show recursiveness in status
If there is an interpolation error, we show the entire trace in our error message. This will cause the message to show the same value many times (in this case 6) with no helpful context (one message with the value would do just fine).

This is what we currently see - 
```
- conditions:
  - lastTransitionTime: "2022-04-15T17:12:17Z"
    message: |-
      unable to stamp object for resource [deployer] in supply chain [supply-chain]: failed to recursively evaluate template: failed to interpolate map value [map[deploy:[map[kapp:map[]]] fetch:[map[inline:map[paths:map[manifest.yml:---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
      ]]]] serviceAccountName:cartographer-example-registry-creds-sa template:[map[ytt:map[]]]]]: failed to interpolate map value [[map[inline:map[paths:map[manifest.yml:---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
      ]]]]]: failed to interpolate array value [map[inline:map[paths:map[manifest.yml:---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
      ]]]]: failed to interpolate map value [map[paths:map[manifest.yml:---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
      ]]]: failed to interpolate map value [map[manifest.yml:---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
      ]]: failed to interpolate map value [---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
      ]: failed to interpolate leaf node: interpolate tag: evaluate jsonpath: jsonpath returned empty list: images.image.image
    reason: TemplateStampFailure
    status: "False"
    type: ResourcesSubmitted
```

If we strip away the contents of manifest.yml we are left with - 
```
- conditions:
  - lastTransitionTime: "2022-04-15T17:12:17Z"
    message: |-
      unable to stamp object for resource [deployer] in supply chain [supply-chain]: failed to recursively evaluate template: failed to interpolate map value [map[deploy:[map[kapp:map[]]] fetch:[map[inline:map[paths:map[manifest.yml:---
      <<template>>
      ]]]] serviceAccountName:cartographer-example-registry-creds-sa template:[map[ytt:map[]]]]]: failed to interpolate map value [[map[inline:map[paths:map[manifest.yml:---
      <<template>>
      ]]]]]: failed to interpolate array value [map[inline:map[paths:map[manifest.yml:---
      <<template>>
      ]]]]: failed to interpolate map value [map[paths:map[manifest.yml:---
      <<template>>
      ]]]: failed to interpolate map value [map[manifest.yml:---
      <<template>>
      ]]: failed to interpolate map value [---
      <<template>>
      ]: failed to interpolate leaf node: interpolate tag: evaluate jsonpath: jsonpath returned empty list: images.image.image
    reason: TemplateStampFailure
    status: "False"
    type: ResourcesSubmitted
```
And I think the only thing we really care about is `jsonpath returned empty list: images.image.image`

I would expect to see - 
```
- conditions:
  - lastTransitionTime: "2022-04-15T17:12:17Z"
    message: |-
      unable to stamp object for resource [deployer] in supply chain [supply-chain]: failed to recursively evaluate template: failed to interpolate leaf node: interpolate tag: evaluate jsonpath: jsonpath returned empty list: images.image.image in
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
      rebaseRules:
        - path:
            - metadata
            - annotations
            - serving.knative.dev/creator
          type: copy
          sources: [new, existing]
          resourceMatchers: &matchers
            - apiVersionKindMatcher:
                apiVersion: serving.knative.dev/v1
                kind: Service
        - path:
            - metadata
            - annotations
            - serving.knative.dev/lastModifier
          type: copy
          sources: [new, existing]
          resourceMatchers: *matchers
      
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: $(workload.metadata.name)$
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: cartographer-example-registry-creds-sa
            containers:
              - name: workload
                image: $(images.image.image)$
                securityContext:
                  runAsUser: 1000
```

### PR DESCRIPTION
**Pull request by idoru**
## Changes proposed by this PR

Simplify template jsonpath errors. Instead of returning an error showing every level of recursion into the template structure, a single error indicating the JSONPath into the template is returned instead.

This change also removes recursive template evaluation.

Fixes #814

## Release Note

Simplify JSONPath errors on templates.
Remove undocumented template recursion functionality.

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- [x] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`
- [x] Removed non-atomic or `wip` commits
- [x] Filled in the [Release Note](#Release-Note) section above 
- ~[ ] Modified the docs to match changes ~

### CODE REVIEW

**Comment by emmjohnson** [comment]
FYI - kuttl test was originally introduced here - https://github.com/vmware-tanzu/cartographer/pull/134 for issue - #81

File: pkg/controllers/deliverable_reconciler_test.go [hunk 1]
```diff
@@ -604,6 +604,8 @@ var _ = Describe("DeliverableReconciler", func() {
 						ResourceName:  "some-name",
 						BlueprintName: "some-delivery",
 						BlueprintType: cerrors.Delivery,
+						TemplateName:  "hot-template",
+						TemplateKind:  "SteamTemplate",
```
Comment (squeedee) [inline pkg/controllers/deliverable_reconciler_test.go]: Could you use an actual template name so I'm less confused when reading this?

**Review by squeedee — APPROVED** [review]
