### PR TITLE
[#1315] Fix for workload prematurely being declared unhealthy

### LINKED ISSUE #1315: workloads with lifecycle:tekton templates go healthy==False
### Bug description:
Please provide a clear and concise description of what the bug is.

### Steps to reproduce:
Please provide a set of steps to reproduce the behavior (example):

*    Get a fresh cluster,
 *   Checkout catalog main
  *  Install TAP 1.7.0-build.35
   * Install a basic supply chain
* Then:
```
k create ns foo

k label namespace foo apps.tanzu.vmware.com/tap-ns=""

tanzu apps workload create foo --git-branch main --git-repo https://github.com/vmware-tanzu/application-accelerator-samples --sub-path tanzu-java-web-app --label apps.tanzu.vmware.com/has-tests=true --label app.kubernetes.io/part-of=tanzu-java-web-app --type web -n foo -y --wait
```
 This will fail with the following error:
`Error: Failed to become ready: unable to retrieve outputs for resource [config-writer] in supply chain [source-to-url]: failed to find any healthy object in the set of immutable stamped object`

A few minutes later the workload will show as healthy.

### Expected behavior:
When a workload pairs with a template that is lifecycle:immutable/tekton

If the set of objects that has been stamped out contains at least one object that is in unknown state

Then the workload reports healthy==unknown.

### Actual behavior:
When lifecycle:immutable/tekton

If the set of objects that has been stamped out does not contain at least one object that is in healthy state

Then the workload reports healthy==false.

### PR DESCRIPTION
**Pull request by tbr11**
[PR requirements]: https://github.com/vmware-tanzu/cartographer/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines

## Changes proposed by this PR

closes #1315

For immutable templates, their resource health is conditioned on the most recently stamped object. Prevents workloads stamping immutable templates to immediately be in Ready==False before later flipping to Ready==True.

When ResourcesSubmitted condition is MissingValueAtPath, the message is conditioned on the object's health condition:
- healthy: cannot read value [some-path] from healthy object [some-resource/some-name] in namespace [some-namespace], contact Platform Eng
- unhealthy: cannot read value [some-path] from unhealthy object [some-resource/some-name] in namespace [some-namespace], examine object, particularly whether it is receiving proper inputs
unknown: waiting to read value [some-path] from object [some-resource/some-name] in namespace [some-namespace]

## Release Note

bug fix for statuses on workloads being prematurely marked unhealthy

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- [x] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`
- [x] Removed non-atomic or `wip` commits
- [x] Filled in the [Release Note](#Release-Note) section above
- [x] Added any relevant branches to cherry-pick
~- [ ] Modified the docs to match changes~

### CODE REVIEW

File: pkg/conditions/owner_conditions.go [hunk 1]
```diff
@@ -61,17 +61,31 @@ func TemplateObjectRetrievalFailureCondition(isOwner bool, err error) metav1.Con
...
 	var namespaceMsg string
 	if obj.GetNamespace() != "" {
 		namespaceMsg = fmt.Sprintf(" in namespace [%s]", obj.GetNamespace())
 	}
+
+	var message string
+
+	switch health {
+	case metav1.ConditionTrue:
+		message = fmt.Sprintf("cannot read value [%s] from healthy object [%s/%s]%s, contact Platform Eng",
```
Comment (tbr11) [inline pkg/conditions/owner_conditions.go:74]: Nitpick: I'd suggest "contact your Platform Engineer" so the user knows it's an operator resolution and not a cartographer bug

**Review by idoru — APPROVED** [review]
