### PR TITLE
Pass DOCKER_CONFIG along to docker-login.sh

### LINKED ISSUE #206: hack: setup.sh overrides ~/.docker/config.json when setting up cluster
### Bug description:

When bringing up a local cluster with `./hack/setup.sh cluster`, `~/.docker/config.json` gets completely overwritten with just the configuration for the local registry.

### Steps to reproduce:

1. have _something_ in ~/.docker/config.json

```bash
printf '{"foo":"bar"}' > ~/.docker/config.json 
```

2. run  the local cluster setup command

```bash
./hack/setup.sh cluster
```

3. notice that we got the previous contents of `~/.docker/config.json` wiped out in favor of the new auth

```bash
cat ~/.docker/config.json | jq '.' -c
```
```console
{"auths":{"10.188.0.3:5000":{"auth":"YWRtaW46YWRtaW4="}}}
```

### Expected behavior:

Rather than having `~/.docker/config.json` overwritten, have the credentials actually going to the intended temporary location as intended by https://github.com/vmware-tanzu/cartographer/pull/175

### Versions:

as of 9e1da8b876db3ba616184ad39310f61161db65f8 (i.e., current `main`)

### Additional context:

I'm almost sure the issue arises from the lack of passing the `DOCKER_CONFIG` variable 

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/setup.sh#L28

down to the environment of `docker-login.sh`

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/docker-login.sh#L21

when executing it

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/setup.sh#L140-L143

to propagate that env down without making it globally exported, we could use the same pattern as in here

https://github.com/vmware-tanzu/cartographer/blob/9e1da8b876db3ba616184ad39310f61161db65f8/hack/setup.sh#L90

where we use `/usr/bin/env` to do so (see [man 1 env](https://man7.org/linux/man-pages/man1/env.1.html))

### PR DESCRIPTION
**Pull request by idoru**
This avoids clobbering ~/.docker/config.json

[#206]

### CODE REVIEW

File: hack/setup.sh [hunk 1]
```diff
@@ -137,9 +137,10 @@ start_registry() {
         password: admin
         "
 
-        DOCKER_USERNAME=admin \
+        env DOCKER_USERNAME=admin \
```
Comment (cirocosta) [inline hack/setup.sh:140]: IIUC, we're successfully authenticating using that config file in DOCKER_CONFIG, but lacking the use of it in other commands that interact with a registry (i.e., `ko`,`imgkpg`)

from CI:

```
~/work/cartographer/cartographer
2021/10/09 22:30:01 No matching credentials were found, falling back on anonymous
2021/10/09 22:30:02 Using base gcr.io/paketo-buildpacks/run:tiny-cnb for github.com/vmware-tanzu/cartographer/cmd/cartographer
2021/10/09 22:30:02 No matching credentials were found for "gcr.io/paketo-buildpacks/run", falling back on anonymous
2021/10/09 22:30:02 Building github.com/vmware-tanzu/cartographer/cmd/cartographer for linux/amd64
2021/10/09 22:31:40 Publishing 10.1.0.112:5000/cartographer:latest
2021/10/09 22:31:40 error processing import paths in "-": error resolving image references: HEAD http://10.1.0.112:5000/v2/cartographer/blobs/sha256:096b763e2e1c4f513b3b57b82339a653361a328653e9b7b2d4c2afe33796a7ed: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
Error: Process completed with exit code 1.
```

we can see `ko` failing there, but I'd imagine any `imgkg` step would do the same

Comment (idoru) [reply hack/setup.sh:140]: Yes, should be fixed now 👍

**Review by cirocosta — APPROVED** [review]
